/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "principal1.h"

void
principal1_1(char * host, int op) {
  CLIENT * clnt;
  char * * result_1;
  struct Datosentrada calculadora_horoscopo_1_arg;
  char * * result_2;
  int horoscopo_semana_1_arg;
  char * * result_3;
  int compatibilidad_horoscopo_1_arg;
  char * * result_4;
  struct Datosentrada horoscopo_chino_1_arg;

  char resultado[9999];

  #ifndef DEBUG
  clnt = clnt_create(host, PRINCIPAL1, PRINCIPAL1_VER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
  #endif /* DEBUG */

  /*========================================================*/
  switch (op) {

  case 1:

    system("clear");

    printf("\n   Introduzca d%ca: ", 161);
    scanf("%d", &calculadora_horoscopo_1_arg.d);
    printf("\n   Introduzca mes: ");
    scanf("%d", &calculadora_horoscopo_1_arg.m);
    printf("\n   Introduzca a%co: ", 164);
    scanf("%d", &calculadora_horoscopo_1_arg.a);
  
    result_1 = calculadora_horoscopo_1( & calculadora_horoscopo_1_arg, clnt);
    if (result_1 == (char ** ) NULL) {
       clnt_perror(clnt, "call failed");
    }

    sprintf(resultado,"%s", (char *) *result_1);
    printf("%s", resultado);

    /**/

    /**/

    break;
    /****************************************************************************************/
  case 2:

    system("clear");
    printf("--Escoja su signo--\n");
    printf("1.- Piscis\n");
    printf("2.- Tauro\n");
    printf("3.- Geminis\n");
    printf("4.- Cancer\n");
    printf("5.- Leo\n");
    printf("6.- Virgo\n");
    printf("7.- Librar\n");
    printf("8.- Escorpion\n");
    printf("9.- Sagitario\n");
    printf("10.- Capricornio\n");
    printf("11.- Acuario\n");
    printf("12.- Aries\n");
    printf("0.- Salir\n");
    scanf("%i", &horoscopo_semana_1_arg);
    fflush(stdin);

     result_2 = horoscopo_semana_1( & horoscopo_semana_1_arg, clnt);
     if (result_2 == (char ** ) NULL) {
                clnt_perror(clnt, "call failed");
     }
     

    sprintf(resultado,"%s", (char *) *result_2);
    printf("%s", resultado);
    break;

    /****************************************************************************************/
  case 3:

    system("clear");
    printf("--Escoja su signo--\n");
    printf("1.- Piscis\n");
    printf("2.- Tauro\n");
    printf("3.- Geminis\n");
    printf("4.- Cancer\n");
    printf("5.- Leo\n");
    printf("6.- Virgo\n");
    printf("7.- Librar\n");
    printf("8.- Escorpion\n");
    printf("9.- Sagitario\n");
    printf("10.- Capricornio\n");
    printf("11.- Acuario\n");
    printf("12.- Aries\n");
    printf("0.- Salir\n");
    scanf("%i", & compatibilidad_horoscopo_1_arg);
    fflush(stdin);

    result_3 = compatibilidad_horoscopo_1( & compatibilidad_horoscopo_1_arg, clnt);
        if(result_3==(char ** ) NULL) {
                   clnt_perror(clnt, "call failed");
     }

    sprintf(resultado,"%s", (char *) *result_3);
    printf("%s", resultado);

    break;
    /********************************************************************************/
  case 4:

    system("clear");
    printf("horoscopo chino\n");
    printf("\n   Introduzca d%ca: ", 161);
    scanf("%d",&horoscopo_chino_1_arg.d);
    printf("\n   Introduzca mes: ");
    scanf("%d",&horoscopo_chino_1_arg.m);
    printf("\n   Introduzca a%co: ", 164);
    scanf("%d",&horoscopo_chino_1_arg.a);

    printf("Introduzca: 1) si es hombre -- 2) si es mujer\t");
    scanf("%d",&horoscopo_chino_1_arg.genero);

    //horoscopo_chino(d, m, a, genero);
    result_4 = horoscopo_chino_1( & horoscopo_chino_1_arg, clnt);
       if(result_4 == (char ** ) NULL) {
         clnt_perror(clnt, "call failed");
       }


    sprintf(resultado,"%s", (char *) *result_4);
    printf("%s", resultado);
    break;
  }

  /*********************************************************/

  



  #ifndef DEBUG
  clnt_destroy(clnt);
  #endif /* DEBUG */

}

int
main(int argc, char * argv[]) {
  char * host;

  if (argc < 2) {
    printf("usage: %s server_host\n", argv[0]);
    exit(1);
  }
  /*====================================================*/

  /********************************************/

  int respt;

  printf("--Servicios--\n");
  printf("1.- Calculadora de signo del zodiaco\n");
  printf("2.- Horóscopo de la semana\n");
  printf("3.- Compatibilidad entre Signos\n");
  printf("4.- Conoce tu Horóscopo chinoy tu galleta\n");
  printf("5.- Salir\n");
  printf("Respuesta: ");
  scanf("%i", & respt);
  fflush(stdin);

  host = argv[1];
  principal1_1(host, respt);
  exit(0);
}