/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "principal1.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mysql/mysql.h>


char **
calculadora_horoscopo_1_svc(struct Datosentrada *argp, struct svc_req *rqstp)
{
	static char * result;

	/***************************/
      int d,m;
      d=argp->d;
      m=argp->m;
      char cadena[1000];

			/*************acuario ***********/
	  if(d>=20 && m==1){
	       	//Enero 20 – Febrero 18-> acuario
	        strcpy(cadena, "sus signo es acuario");
    	}
		else if(d<=18 && m==2){
			//Enero 20 – Febrero 18-> acuario
	        strcpy(cadena,"sus signo es acuario");
		}
		
		
		
		/*************piscis ***********/
		else if(d>=19 && m==2){
	     	//Febrero 19 – Marzo 20
	        strcpy(cadena,"sus signo es piscis");
    	}
	    
	    else if(d<=20 && m==3){
			//Febrero 19 – Marzo 20
	        strcpy(cadena,"sus signo es piscis");
		}
		
		
		/************* aries ***********/
		else if(d>=21 && m==3){
		      //Marzo 21 –Abril 19
	            strcpy(cadena,"sus signo es aries");
      	}
	    else if(d<=19 && m==4){
		    	//Marzo 21 –Abril 19
	            strcpy(cadena,"sus signo es aries");
		}
	
	
	   		/************* tauro ***********/
		 else if(d>=20 && m==4){
	          //Abril 20 – Mayo 20-> tauro
	          strcpy(cadena,"sus signo es tauro");
	    }
	    else if(d<=20 && m==5){
		        //Abril 20 – Mayo 20-> tauro
	            strcpy(cadena,"sus signo es tauro");
		}
		
		/************* geminis ***********/
		else if(d>=21 && m==5){
	        		//Mayo 21 – Junio 20 -> geminis
	             strcpy(cadena,"sus signo es geminis");
     	}
	    else if(d<=20 && m==6){
		        	//Mayo 21 – Junio 20 -> geminis
	                strcpy(cadena,"sus signo es geminis");
		}


       	/************* cancer ***********/
		else if(d>=21 && m==6){
		        	//Junio 21 – Julio 22-> cancer
	            strcpy(cadena,"sus signo es cancer");   
    	}	
    	else if(d<=22 && m==7){
		         	//Junio 21 – Julio 22-> cancer
	            strcpy(cadena,"sus signo es cancer");  
		}
		
		/*************leo ***********/
	     else if(d>=23 && m==7){
		            //Julio 23–Agosto 22-> leo
	                strcpy(cadena,"sus signo es leo"); 
    	}
	    else if(d<=22 && m==8){
	           		  //Julio 23–Agosto 22-> leo
	            strcpy(cadena,"sus signo es leo"); 
		}
	
	
	   /************* virgo **********************/
		else if(d>=23 && m==8){
		       //Agosto 23 – Septiembre 22-> virgo
	           strcpy(cadena,"sus signo es virgo");
    	}
    	else if(d<=22 && m==9){
			//Agosto 23 – Septiembre 22-> virgo
	           strcpy(cadena,"sus signo es virgo");
		}
		
		
		
		/************ libra ************/
		else if(d>=23 && m==9){
		    //Septiembre 23 – Octubre 22-> libra
	        strcpy(cadena,"sus signo es libra");
	    }
	    else if(d<=22 && m==10){
		   //Septiembre 23 – Octubre 22-> libra
	        strcpy(cadena,"sus signo es libra");
		}
	
	/****************** escorpion ********************/
		else if(d>=23 && m==10){
		    //Octubre 23 – Noviembre 21-> escorpion
	        strcpy(cadena,"sus signo es escorpion");
	    }
	     else if(d<=21 && m==11){
		  //Octubre 23 – Noviembre 21-> escorpion
	        strcpy(cadena,"sus signo es escorpion");
		}
		
		/*****************sagitario**********************/
		else if(d>=22 && m==11){
		   	//Noviembre 22 - Diciembre 21-> sagitario
	        strcpy(cadena,"sus signo es sagitario");
     	}
     	else if(d<=22 && m==12){
			//Noviembre 22 - Diciembre 21-> sagitario
	        strcpy(cadena,"sus signo es sagitario");
		}
	   
	    /********************* sagitario ***********************/
		else if(d>=20 && m==1){
		  //Enero 20 – Febrero 18-> acuario
	      strcpy(cadena,"sus signo es acuario");
	    }
	    else if(d<=18 && m==2){
			//Enero 20 – Febrero 18-> acuario
	        strcpy(cadena,"sus signo es acuario");
		}
	
	 /**************** capricornio ******************/
		else if(d>=22 && m==12){
		    //Diciembre 22 – Enero 19-> capricornio
	        strcpy(cadena,"sus signo es capricornio");
	    }
	    else if(d<=19 && m==1){
			 //Diciembre 22 – Enero 19-> capricornio
	        strcpy(cadena,"sus signo es capricornio");
		}
	/***************************/
    result=strdup(cadena);
	return &result;
}




/*segundo servicio*/
char **
horoscopo_semana_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	int a;
	a=*argp;
	char resultado[9999];

	
	/******************conexion**********************/
 	system("clear");
	MYSQL *conn,mysql; /* variable de conexión para MySQL */
	MYSQL_RES *res; /* variable que contendra el resultado de la consuta */
	MYSQL_ROW row; /* variable que contendra los campos por cada registro consultado */
	char *server = "127.0.0.1"; /*direccion del servidor 127.0.0.1, localhost o direccion ip */
	char *user = "root"; /*usuario para consultar la base de datos */
	char *password = ""; /* contraseña para el usuario en cuestion */
	char *database = "horoscopo"; /*nombre de la base de datos a consultar */
	conn = mysql_init(&mysql); /*inicializacion a nula la conexión */
  	mysql_options(&mysql, MYSQL_SET_CHARSET_NAME, "utf8");
	mysql_options(&mysql, MYSQL_INIT_COMMAND, "SET NAMES utf8");

	/* conectar a la base de datos */
	if (!mysql_real_connect(conn, server, user, password, database, 0, NULL, 0))
	{ /* definir los parámetros de la conexión antes establecidos */
		fprintf(stderr, "%s\n", mysql_error(conn)); /* si hay un error definir cual fue dicho error */
		exit(1);
	}
/*************************************************/

	switch(a){
				
case 1:
 
 	   //printf("piscis");

 /******** enviar consulta SQL *****/

    /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,semanal from signo where id_signo=8"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){


        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);


    }

    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
   break;

case 2:
    //printf("tauro");

    /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=10"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;

case 3:
    //printf("geminis");

    /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=8"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		
 case 4:
    //printf("cancer");

    /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=12"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		
case 5:
    //printf("leo");

    /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=1"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		
 case 6:
    //printf("libra");

    /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=3"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		
case 7:
    //printf("escorpion");

   /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=4"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		
 case 8:
    	//printf("sagitario");

     /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=5"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		

  case 9:
    		//printf("capricornio");

      /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=6"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		
 case 10:
    		//printf("acuario");

     /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=7"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		
 case 11:
    		//printf("aries");

     /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=9"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);
    }
    mysql_free_result(res);
	mysql_close(conn);
/***********************************/
    		break;
    		
    		
 case 12:

    	    //printf("virgo");
     
     /******** enviar consulta SQL *****/
	if (mysql_query(conn, "select nombre,color,personalidad,elemento,semanal from signo where id_signo=2"))
	{ /* definicion de la consulta y el origen de la conexion */
		fprintf(stderr, "%s\n", mysql_error(conn));
		exit(1);
	}
    
     res=mysql_use_result(conn);
     //printf("Nombre\t\tcolor\n");
     //obtiene los resultados
    if((row=mysql_fetch_row(res))!=NULL){
        strcat(resultado, "\nNombre: ");
		strcat(resultado, row[0]);
		strcat(resultado, "\nColor: ");
		strcat(resultado, row[1]);
		strcat(resultado, "\npersonalidad: ");
		strcat(resultado, row[2]);
		strcat(resultado, "\nElemento: ");
		strcat(resultado, row[3]);
		strcat(resultado, "\nSemanal: ");
		strcat(resultado, row[4]);

 }

    mysql_free_result(res);
	mysql_close(conn);
     break;


       }

    
    result=resultado;
	return &result;
}

char **
compatibilidad_horoscopo_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
horoscopo_chino_1_svc(struct Datosentrada *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}
