/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "principal1.h"

bool_t
xdr_Datosentrada (XDR *xdrs, Datosentrada *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->d))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->m))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->a))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->genero))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->d);
			IXDR_PUT_LONG(buf, objp->m);
			IXDR_PUT_LONG(buf, objp->a);
			IXDR_PUT_LONG(buf, objp->genero);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->d))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->m))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->a))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->genero))
				 return FALSE;
		} else {
			objp->d = IXDR_GET_LONG(buf);
			objp->m = IXDR_GET_LONG(buf);
			objp->a = IXDR_GET_LONG(buf);
			objp->genero = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->d))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->m))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->genero))
		 return FALSE;
	return TRUE;
}
