/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRINCIPAL1_H_RPCGEN
#define _PRINCIPAL1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Datosentrada {
	int d;
	int m;
	int a;
	int genero;
};
typedef struct Datosentrada Datosentrada;

#define PRINCIPAL1 1
#define PRINCIPAL1_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define calculadora_horoscopo 1
extern  char ** calculadora_horoscopo_1(struct Datosentrada *, CLIENT *);
extern  char ** calculadora_horoscopo_1_svc(struct Datosentrada *, struct svc_req *);
#define horoscopo_semana 2
extern  char ** horoscopo_semana_1(int *, CLIENT *);
extern  char ** horoscopo_semana_1_svc(int *, struct svc_req *);
#define compatibilidad_horoscopo 3
extern  char ** compatibilidad_horoscopo_1(struct Datosentrada *, CLIENT *);
extern  char ** compatibilidad_horoscopo_1_svc(struct Datosentrada *, struct svc_req *);
#define horoscopo_chino 4
extern  char ** horoscopo_chino_1(struct Datosentrada *, CLIENT *);
extern  char ** horoscopo_chino_1_svc(struct Datosentrada *, struct svc_req *);
extern int principal1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calculadora_horoscopo 1
extern  char ** calculadora_horoscopo_1();
extern  char ** calculadora_horoscopo_1_svc();
#define horoscopo_semana 2
extern  char ** horoscopo_semana_1();
extern  char ** horoscopo_semana_1_svc();
#define compatibilidad_horoscopo 3
extern  char ** compatibilidad_horoscopo_1();
extern  char ** compatibilidad_horoscopo_1_svc();
#define horoscopo_chino 4
extern  char ** horoscopo_chino_1();
extern  char ** horoscopo_chino_1_svc();
extern int principal1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Datosentrada (XDR *, Datosentrada*);

#else /* K&R C */
extern bool_t xdr_Datosentrada ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRINCIPAL1_H_RPCGEN */
